image: docker:19.03.12

stages:
  - test
  - visualize
  - build
  - package
  - deploy

variables:
  CONTAINER_NAME: user-service
  ENVIRONMENT: dev
  JACOCO_CSV_LOCATION: '$CI_PROJECT_DIR/build/jacoco/jacocoCsv'

test:
  image: gradle:6.9.0-jdk11
  stage: test
  script:
    - gradle test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' $JACOCO_CSV_LOCATION
  artifacts:
    paths:
      - build/jacoco/jacoco.xml

coverage:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py build/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > build/cobertura.xml
  dependencies:
    - test
  artifacts:
    reports:
      cobertura: build/cobertura.xml

build:
  image: gradle:6.9.0-jdk11
  stage: build
  script:
    - gradle build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    policy: push
    paths:
      - build/libs/*.jar

package-docker-image:
  stage: package
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    policy: pull
    paths:
      - build/libs/*.jar
  script:
    - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_HUB_ID/$IMAGE_NAME .
    - docker push $DOCKER_HUB_ID/$IMAGE_NAME

g238_deploy:
  stage: deploy
  tags:
    - g238
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - "{ docker stop $CONTAINER_NAME; docker rm $CONTAINER_NAME; } || true"
    - "docker run -d -p $SERVICE_PORT:$SERVICE_PORT \
    --name $CONTAINER_NAME \
    -e HOST_IP=$HOST_238_IP \
    -e CONFIG_SERVER_URL=$CONFIG_SERVER_URL \
    -e spring.profiles.active=$ENVIRONMENT \
    $DOCKER_HUB_ID/$IMAGE_NAME"

g239_deploy:
  stage: deploy
  tags:
    - g239
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - "{ docker stop $CONTAINER_NAME; docker rm $CONTAINER_NAME; } || true"
    - "docker run -d -p $SERVICE_PORT:$SERVICE_PORT \
    --name $CONTAINER_NAME \
    -e HOST_IP=$HOST_239_IP \
    -e CONFIG_SERVER_URL=$CONFIG_SERVER_URL \
    -e spring.profiles.active=$ENVIRONMENT \
    $DOCKER_HUB_ID/$IMAGE_NAME"

g240_deploy:
  stage: deploy
  tags:
    - g240
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - "{ docker stop $CONTAINER_NAME; docker rm $CONTAINER_NAME; } || true"
    - "docker run -d -p $SERVICE_PORT:$SERVICE_PORT \
    --name $CONTAINER_NAME \
    -e HOST_IP=$HOST_240_IP \
    -e CONFIG_SERVER_URL=$CONFIG_SERVER_URL \
    -e spring.profiles.active=$ENVIRONMENT \
    $DOCKER_HUB_ID/$IMAGE_NAME"