server:
  port: 30040

spring:
  application:
    name: user-service
  messages:
    basename: errors
  datasource:
    url: jdbc:mysql://10.7.27.19:3306/fluentd-test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: SecretKey
  expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST_IP}"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.7.27.18:8761/eureka,http://10.7.27.19:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh