server:
  port: 30040

spring:
  application:
    name: user-service
  messages:
    basename: errors
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: SecretKey
  expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST_IP}"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.7.27.18:8761/eureka,http://10.7.27.19:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
